separating android workflow

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -60,54 +60,54 @@ workflows:
         - /tmp/xcodebuild_logs/*.log
         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
-  # react-native-android:
-  #   name: React Native Android
-  #   max_build_duration: 120
-  #   instance_type: mac_mini_m2
-  #   environment:
-  #     android_signing:
-  #       - codemagic_keystore
-  #     # groups:
-  #     #   - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json)
-  #     vars:
-  #       PACKAGE_NAME: "io.codemagic.expoapp" # <-- Put your package name here e.g. com.domain.myapp
-  #     java: 17
-  #   triggering:
-  #     events:
-  #         - push
-  #         - tag
-  #         - pull_request
-  #     branch_patterns:
-  #         - pattern: develop
-  #           include: true
-  #           source: true
-  #   scripts:
-  #     - name: Install dependencies and set up app
-  #       script: |
-  #          yarn install --legacy-peer-deps
-  #          npx expo prebuild
+  react-native-android:
+    name: React Native Android
+    max_build_duration: 120
+    instance_type: linux_x2
+    environment:
+      android_signing:
+        - codemagic_keystore
+      # groups:
+      #   - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json)
+      vars:
+        PACKAGE_NAME: "io.codemagic.expoapp" # <-- Put your package name here e.g. com.domain.myapp
+      java: 17
+    triggering:
+      events:
+          - push
+          - tag
+          - pull_request
+      branch_patterns:
+          - pattern: develop
+            include: true
+            source: true
+    scripts:
+      - name: Install dependencies and set up app
+        script: |
+           yarn install --legacy-peer-deps
+           npx expo prebuild
 
-  #     # - name: Set up app/build.gradle
-  #     #   script: |
-  #     #     mv ./support-files/build.gradle android/app
-  #     - name: Set Android SDK location
-  #       script: |
-  #         echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"          
-  #     - name: Build Android release
-  #       script: |
-  #         LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-  #         if [ -z LATEST_BUILD_NUMBER ]; then
-  #             # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
-  #             UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-  #         else
-  #             UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-  #         fi
-  #         cd android
-  #         ./gradlew bundleRelease \
-  #           -PversionCode=$UPDATED_BUILD_NUMBER \
-  #           -PversionName=1.0.$UPDATED_BUILD_NUMBER
-  #   artifacts:
-  #       - android/app/build/outputs/**/*.aab
+      # - name: Set up app/build.gradle
+      #   script: |
+      #     mv ./support-files/build.gradle android/app
+      - name: Set Android SDK location
+        script: |
+          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"          
+      - name: Build Android release
+        script: |
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+          if [ -z LATEST_BUILD_NUMBER ]; then
+              # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+          else
+              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+          fi
+          cd android
+          ./gradlew bundleRelease \
+            -PversionCode=$UPDATED_BUILD_NUMBER \
+            -PversionName=1.0.$UPDATED_BUILD_NUMBER
+    artifacts:
+        - android/app/build/outputs/**/*.aab
     # publishing:
     #   email:
     #     recipients:
